### ISSUE TITLE
Wow,would you update future

### ISSUE THREAD

**Issue by odarknighto** [kazzmir/paintown#10]
The emulator is so good,it can play mugen by android,but when I add other characters in mugen,it would be very lag,I don't know it's my phone problem or the app problem,hope it will update and be better than all~^^(sorry with poor English)

**Comment by kazzmir** [comment]
The current android version is a prototype. A more mature version will be better.

**Comment by odarknighto** [comment]
I am looking forward for this.Hope we can play it quickly in future
