### ISSUE TITLE
linux compile error 

### ISSUE THREAD

**Issue by fastfading** [kazzmir/paintown#11]
scons: Reading SConscript files ...
Build type: Allegro5
OSError: 'pkg-config r-tech1 --cflags --libs' exited 1:
  File "/home/hui/git/paintown/SConstruct", line 1472:
    scons.utils.safeParseConfig(env, 'pkg-config r-tech1 --cflags --libs')
  File "/home/hui/git/paintown/scons/utils.py", line 120:
    version1()
  File "/home/hui/git/paintown/scons/utils.py", line 109:
    raise e
Get scons at www.scons.org or read the README for compilation instructions
Makefile:9: recipe for target 'all' failed
make: **\* [all] Error 1
ls: cannot access 'paintown': No such file or directory
Here is the executable. To run it type: ./paintown

r-tech1  did not exist in the repo
Cmake did not work too.

**Comment by fastfading** [comment]
I am using sdl but some how this Build type:=Allegro5
mac has the same problem

**Comment by xuyan505** [comment]
**I also came across the same problem.**
scons: Reading SConscript files ...
Build type: Allegro5
OSError: 'pkg-config r-tech1 --cflags --libs' exited 1:
  File "/home/xuyan505/Desktop/paintown-master/paintown-master/SConstruct", line 1472:
    scons.utils.safeParseConfig(env, 'pkg-config r-tech1 --cflags --libs')
  File "/home/xuyan505/Desktop/paintown-master/paintown-master/scons/utils.py", line 120:
    version1()
  File "/home/xuyan505/Desktop/paintown-master/paintown-master/scons/utils.py", line 109:
    raise e
Get scons at www.scons.org or read the README for compilation instructions
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 1
ls: cannot access 'paintown': No such file or directory
Here is the executable. To run it type: ./paintown

**Comment by kazzmir** [comment]
r-tech1 is a separate repo. http://github.com/kazzmir/r-tech1. Build it and install it

**Comment by fastfading** [comment]
It seems  paintown mugen ai is stupid.
And it did not support errors handling like mugen.
many character runs well on mugen but , crash in paintown.
What is missing in paintown?

2016-11-09 8:44 GMT+08:00 Jon Rafkind <notifications@github.com>:

**Comment by fastfading** [comment]
One more thing ,  is paintown support mod game in openbor?
I see there is a folder called openbor
Are these 2 compatitable?


2016-11-09 8:44 GMT+08:00 Jon Rafkind <notifications@github.com>:

**Comment by kazzmir** [comment]
openbor support is not complete. It was started as a prototype.

**Comment by fastfading** [comment]
I notice there is some python script like peg_air.py peg_def.py peg_cns.py
peg_cmd.py.......   to parse mugen data.
And there are also related cpp code.  And there are yy files parse-air.yy
parse-cmd.yy .
I am confused.  I am using the svn code .
Which parser are actually being used ,  cpp or python or yy  ,
my build environment is as below -- "Checking if python is embeddable...
(cached) no"
There seems many bugs in this parse process,  I am trying to fix it .
Pls help
Thank you very much

scons: Reading SConscript files ...
Build type: SDL
Checking for threads... (cached)  pthreads(cached) yes
Checking for SDL ... (cached) yes
Checking for SDL main... (cached) no
Checking for C header file ft2build.h... (cached) yes
Checking for C header file png.h... (cached) yes
Checking if we need rtti... (cached) no
Checking for ogg and vorbis... (cached) yes
Checking for libmpg123... (cached) no
Checking for libmad... (cached) no
Checking for static SDL... (cached) yes
Checking for SDL main... (cached) no
Checking for threads... (cached)  pthreads(cached) yes
Checking if we need rtti... (cached) yes
Checking if python is embeddable... (cached) no
Checking if python is embeddable... (cached) no
Checking if python is embeddable... (cached) no
Checking if python is embeddable... (cached) no
Checking if python is embeddable... (cached) no
Checking if python is embeddable... (cached) no
Checking if python is embeddable... (cached) no
Checking if python is embeddable... (cached) no


2016-11-11 3:33 GMT+08:00 Jon Rafkind <notifications@github.com>:

**Comment by kazzmir** [comment]
The yy files are not used. The .peg files are grammar files meant to be
input to the parser generator tool, which is peg.py (and some related .py
files). The input files are converted into C++ code such as def.cpp,
cmd.cpp, and air.cpp. The C++ code is what actually contains the parsers.

The embeddable python checks have nothing at all to do with the creation of
the parsers. The embedded python stuff is for allowing the paintown engine
to be scripted via python. The mugen engine does not support python
scripting.

**Comment by fastfading** [comment]
Thank you very much .
So when I want to change the parser ,
I should change peg_air.py peg_def.py peg_cns.py peg_cmd.py  these files
 right?


2016-11-11 10:56 GMT+08:00 Jon Rafkind <notifications@github.com>:

**Comment by kazzmir** [comment]
You should change the .peg files, not the .py files.

**Comment by fastfading** [comment]
what are these peg_air.py peg_def.py peg_cns.py peg_cmd.py used for?
Are they abandon too?

2016-11-11 11:08 GMT+08:00 Jon Rafkind <notifications@github.com>:

**Comment by kazzmir** [comment]
The peg_*.py files are generated by the parser generator while it
bootstraps itself. First peg.py generates a parser generator for reading
the .peg files themselves based on a description in python itself inside
peg.py. The parser generated by peg.py is capable of creating a model of
the .peg files which is used to generate the parsers they describe. Those
parsers are compiled into the C++ parsers that are actually used. There is
no sense in touching the peg_*.py files. When I refer to peg.py and the
.peg files I am referring to the files in paintown/src/mugen/parser

**Comment by fastfading** [comment]
Are  python run in the program runtime?
In other words ,  did this program depend on python "after" its compiled?
Or just rely on it before compile, only use python to generate cpp files.



2016-11-11 11:14 GMT+08:00 Jon Rafkind <notifications@github.com>:

**Comment by kazzmir** [comment]
Python is only used to generate the cpp files.
