### ISSUE TITLE
Compilation error with gcc

### ISSUE THREAD

**Issue by svenstaro** [kazzmir/paintown#16]
On Arch Linux with gcc 7.2.1 I get the attached problem.
[log.txt](https://github.com/kazzmir/paintown/files/1597011/log.txt)

**Comment by svenstaro** [comment]
Same error when running this with scons, by the way.

**Comment by sagitter** [comment]
Same error for me; GCC-7.3.1 on Fedora 27.

**Comment by kazzmir** [comment]
This is fixed in 4ae6fe7a0038297fe325f014fed9cfbf45613dcf in the r-tech1 repo. In latest master the src/util directory was split into a separate repo named r-tech1.

**Comment by sagitter** [comment]
Does `paintown` require `r-tech1` libraries then?

**Comment by kazzmir** [comment]
master does
