### ISSUE TITLE
I can not change the resolution

### ISSUE THREAD

**Issue by asknofar** [kazzmir/paintown#2]

**Comment by kazzmir** [comment]
Do you mean in the options menu? You can always just adjust the size of the screen by moving the window border.

**Comment by asknofar** [comment]
but the Android version ... looks bigger than my screen

**Comment by asknofar** [comment]
You can not change the screen size on android version ...

**Comment by kazzmir** [comment]
I understand. I will look into it.

**Comment by EvilQU3S4D1LL4S** [comment]
Still havimg this issue literally..

**Comment by asknofar** [comment]
There is no need to worry, I have changed my device and the resolution
fits me very well ... now I can play more than good ... thank you very
much

2018-03-19 9:42 GMT-03:00, OG <notifications@github.com>:

**Comment by juvinious** [comment]
If you are using 3.6.0 you are not going to be able to change the resolution. 
You'll need to use the master branch which is using Allegro5 instead of SDL.

> Still havimg this issue literally..
