### ISSUE TITLE
User friendly installation on Linux?

### ISSUE THREAD

**Issue by WPFilmmaker** [kazzmir/paintown#20]
First of all thank you for the great software!
I have a question, is there a user friendly way to install paintown on linux? I couldn't find any deb package fo my distro, nor a ppa..I tried in the software center but there is no paintown. It is a pity that linux users have to compile from source..more players would enjoy paintown if it could be just downloaded and installed.
ps: I tried with Wine and it runs but it is buggy and unplayable :/

**Comment by juvinious** [comment]
Not at the moment unless someone wants to create a package and support it.
Your best bet is to take the [3.6.0 release](https://github.com/kazzmir/paintown/releases/tag/v3.6.0) source (assuming your distro is ubuntu/debian) and run the script easy-compile-ubuntu. It should install necessary libraries and build it for you.
