### ISSUE TITLE
Is the PSP build still supported?

### ISSUE THREAD

**Issue by Lykie** [kazzmir/paintown#25]
I've been looking for anything related to it, and there seems to be no downloads. Apparently the source might still allow it to be built, but I want to know if it's supported before I delve into that.

**Comment by kazzmir** [comment]
The psp version was just a prototype but never really worked due to the lack of pre-emptive multithreading in the psp hardware.

**Comment by Lykie** [comment]
Ah, that makes sense. Thanks for replying.
