### ISSUE TITLE
'contact' tag in editor

### ISSUE THREAD

**Issue by ghost** [kazzmir/paintown#26]
Hi,

I use the editor to create characters for Paintown.
I prefer using the 'contact' tag instead of hit-sound, since I can use a much larger variety of sounds that way.

Unfortunately the editor does not recognize this tag, and thus strips it whenever I edit and save the character.

Could you please add support for it?

Regards

**Comment by RalfVB** [comment]
Is this project alive?

**Comment by kazzmir** [comment]
I don't have a lot of time for this project these days.

**Comment by juvinious** [comment]
The editor would need to be redone. Not currently planned at the moment.
