### ISSUE TITLE
MUGEN questions

### ISSUE THREAD

**Issue by sulram** [kazzmir/paintown#27]
1) Is it possible to use Paintown as MUGEN only, automatically loading MUGEN mode?
2) How to edit Mugen Motifs (intro, screen packs, etc)?
3) I had to change some lines from my chars .def file (removed localcoords, for example). I was using version 1.0. Stages didn't work. What version of Mugen Paintown uses?

**Comment by Barklim** [comment]
maybe someday they will answer :(

**Comment by sulram** [comment]
> maybe someday they will answer :(

I'm taking a look at IKEMEN GO PLUS

**Comment by Barklim** [comment]
Thanks for the answer! I ask because I am interested in the task of compiling the source code in wasm, in order to run the compiled code in the browser. It would be great if it could be done. You could play mugen online. Since the source code for the original mugen is not available, paintown or KOF 91 might work well for this task. Thanks a lot for the tip.

**Comment by Barklim** [comment]
it is unlikely that the source code will ever appear :(

**Comment by sulram** [comment]
@Barklim let's keep in touch. I also want to bring Mugen to the browser, it would be awesome. I was thinking about porting it to Rust.

**Comment by Barklim** [comment]
Fine! I am ready for cooperation. I would like to share possibly interesting information. As you know, in creating your own assembly, it is easy to draw rosters, import your music, character icons, but the most difficult thing is to correctly create a character sprite sheet. There are quite a variety of ways to simplify this work, for example, using a ready-made sprite and an image of one sprite https://www.youtube.com/watch?v=ndRhzzXfIJ4&feature=emb_title. There is a way to create a model in blender and generate a sprite sheet based on the model's poses like on this channel. https://www.youtube.com/channel/UCqQMKmIoOf54NMkV0HOI-6Q.
True, doing it manually is quite time consuming. So there you go! Not long ago, a source project became available that automatically creates a character model from an image https://shunsukesaito.github.io/PIFu/. A similar project for the face https://habr.com/ru/post/406993/. I think it is possible to create a flexible and fast way to generate characters based on these technologies.

**Comment by sulram** [comment]
Cool!!! We are very in sync. I've created a Mugen game in 2018, pixel art style, and I was thinking about AI to style transfer poses... but in pixel art level, don't know if possible, but even with a sketch result, it would save a lot of time... One character is more than 100 frames!

https://streetfliper.itch.io/
https://imgur.com/a/FhIfR3U

**Comment by juvinious** [comment]
You can run mugen mode directly:
```Console
$ paintown mugen
# or 
$ paintown --mugen
```

Support for 1.0 is somewhat there but is limited and buggy.
Fixes for this is are not currently planned at the moment, but it seems you two have found some other alternatives.
