### ISSUE TITLE
Error while compiling on Raspbian

### ISSUE THREAD

**Issue by mike855** [kazzmir/paintown#29]
Hello,

I'm trying to compile on raspbian and have the following error : 

`Compiling header build/allegro5/r-tech1/out/release/libs/gme/Nes_Vrc6_Apu.h
build/allegro5/r-tech1/out/release/libs/gme/Nes_Oscs.h:65:12: error: ‘nes_time_t’ has not been declared
  void run( nes_time_t, nes_time_t );
            ^~~~~~~~~~
build/allegro5/r-tech1/out/release/libs/gme/Nes_Oscs.h:65:24: error: ‘nes_time_t’ has not been declared
  void run( nes_time_t, nes_time_t );
                        ^~~~~~~~~~
build/allegro5/r-tech1/out/release/libs/gme/Nes_Oscs.h:70:2: error: ‘nes_time_t’ does not name a type
  nes_time_t maintain_phase( nes_time_t time, nes_time_t end_time,
  ^~~~~~~~~~
build/allegro5/r-tech1/out/release/libs/gme/Nes_Oscs.h:83:12: error: ‘nes_time_t’ has not been declared
  void run( nes_time_t, nes_time_t );
            ^~~~~~~~~~
build/allegro5/r-tech1/out/release/libs/gme/Nes_Oscs.h:83:24: error: ‘nes_time_t’ has not been declared
  void run( nes_time_t, nes_time_t );
                        ^~~~~~~~~~
build/allegro5/r-tech1/out/release/libs/gme/Nes_Oscs.h:90:2: error: ‘nes_time_t’ does not name a type
  nes_time_t maintain_phase( nes_time_t time, nes_time_t end_time,
  ^~~~~~~~~~
build/allegro5/r-tech1/out/release/libs/gme/Nes_Oscs.h:100:12: error: ‘nes_time_t’ has not been declared
  void run( nes_time_t, nes_time_t );
            ^~~~~~~~~~
build/allegro5/r-tech1/out/release/libs/gme/Nes_Oscs.h:100:24: error: ‘nes_time_t’ has not been declared
  void run( nes_time_t, nes_time_t );
                        ^~~~~~~~~~
build/allegro5/r-tech1/out/release/libs/gme/Nes_Oscs.h:123:2: error: ‘nes_time_t’ does not name a type
  nes_time_t next_irq;
  ^~~~~~~~~~
build/allegro5/r-tech1/out/release/libs/gme/Nes_Oscs.h:129:28: error: ‘nes_addr_t’ has not been declared
  int (*prg_reader)( void*, nes_addr_t ); // needs to be initialized to prg read function
                            ^~~~~~~~~~
build/allegro5/r-tech1/out/release/libs/gme/Nes_Oscs.h:138:12: error: ‘nes_time_t’ has not been declared
  void run( nes_time_t, nes_time_t );
            ^~~~~~~~~~
build/allegro5/r-tech1/out/release/libs/gme/Nes_Oscs.h:138:24: error: ‘nes_time_t’ has not been declared
  void run( nes_time_t, nes_time_t );
                        ^~~~~~~~~~
build/allegro5/r-tech1/out/release/libs/gme/Nes_Oscs.h:143:19: error: ‘nes_time_t’ has not been declared
  int count_reads( nes_time_t, nes_time_t* ) const;
                   ^~~~~~~~~~
build/allegro5/r-tech1/out/release/libs/gme/Nes_Oscs.h:143:31: error: ‘nes_time_t’ has not been declared
  int count_reads( nes_time_t, nes_time_t* ) const;
                               ^~~~~~~~~~
build/allegro5/r-tech1/out/release/libs/gme/Nes_Oscs.h:144:2: error: ‘nes_time_t’ does not name a type
  nes_time_t next_read_time() const;
  ^~~~~~~~~~
scons: *** [build/allegro5/r-tech1/out/release/libs/gme/Nes_Oscs.h.gch] Error 1
scons: building terminated because of errors.
`

**Comment by Askmewho** [comment]
me too, ive tried cmake, but the cmake cant find a lot of things on src folder... its  outdated?

**Comment by juvinious** [comment]
Could you try #38 and see if it builds now?
Use the script for easy build ubuntu, should work for raspbian.
