### ISSUE TITLE
Cannot adjust screen size in Android version.

### ISSUE THREAD

**Issue by supersonicrainboom** [kazzmir/paintown#31]
Is there an option to increase the screen size of Paintown on Android? Im using a Samsung Galaxy S9 and the game window is very small for some reason, And Whenever I go to the Screen Size option in the settings menu, it freezes the game. I attached an image of what it looks like for me.
![Screenshot_20200430-191659_Paintown](https://user-images.githubusercontent.com/31225845/80767988-30f39580-8b17-11ea-907b-420b0e05b603.jpg)

**Comment by kazzmir** [comment]
This requires a code change, I don't think its a configuration change. The android port is quite experimental.
