### ISSUE TITLE
Easy way of Porting platform

### ISSUE THREAD

**Issue by humbertodias** [kazzmir/paintown#58]
## Idea
Instead of adapt the source code to fit into any target platform. 
We could use the libretro core as a shortcut.
Retroarch is already ported to several platform such as: android, iOS, PS3, Xbox, Win, Linux, etc
Supported platforms https://www.retroarch.com/?page=platforms
So, creating a core like libretro-paintown we would have immediately a port of Paintown to all of them.
Luckely that was already made with some libretro cores and could be an inspiration:
1. Jump 'n Bump
* https://github.com/libretro/jumpnbump-libretro
* https://www.youtube.com/watch?v=YHrocZPWiH0

2. Gong
* https://github.com/libretro/gong
* https://www.youtube.com/watch?v=D5ZNwQQA0H8

3. Boom3
* https://github.com/libretro/boom3
* https://www.youtube.com/watch?v=uS7veurg0ww

**Comment by juvinious** [comment]
It's an interesting idea. I think the code base must be cleaned up a bit more and remove some of the old legacy code of previous backends/ports so that something like this can be facilitated. At the moment I think the focus now is getting the SDL2 backend working as it was with Allegro.

**Comment by juvinious** [comment]
This is great. As I mentioned in your easy release ubuntu PR, it would eventually be nice to create an [AppImage](https://docs.appimage.org/) as it'll allow it to be run on any distro. 
I'm going to look into it further and just create a separate build script for it.
In the meantime this would help get us to create a new release sooner. 
Thanks!

**Comment by juvinious** [comment]
Ok, following up on this I don't think this is going to be possible as libretro is dependent on c99 and we have moved on to c11. 
```
The libretro API consists of several functions outlined in libretro.h, found in the RetroArch source package. The API header is compatible with C99 and C++. From C99, the bool type and <stdint.h> are used. The latest version of this file can be found [in libretro-common](https://github.com/libretro/RetroArch/blob/master/libretro-common/include/libretro.h).
```
We can open this back up and revisit if libretro moves on to c11 in the future.
