### ISSUE TITLE
master does not support SDL 

### ISSUE THREAD

**Issue by WilliamTambellini** [kazzmir/paintown#7]
Hi
I have tried : 
- scons: cannot find Allegro 5
- make: cannot find allegro 5
- cmake: cannot cmake because src/util has disappeared

I have tried with 3.6.0 and it build perfectly.
Looks like some third parties have been moved from 'src/util' to 'src/system'.
TBC

**Comment by kazzmir** [comment]
src/util has become the r-tech1 repo. cmake wasn't yet updated to support r-tech1. I'll look into the allegro5 errors soon, but I think it worked for me last time I tried it.

**Comment by kazzmir** [comment]
What version of allegro5 do you have installed? I have 5.1 and scons/make is able to find it. Also you can try

    $ scons verbose=1

And look at config.log for more details

**Comment by WilliamTambellini** [comment]
Hi @kazzmir 
Thanks.
So I dont have any allegro installed and 3.6.0 does compile using sdl.
I have cloned rtech1 but dont see any master CMakeLists.txt : 
- is there any cmake script to compile rtech1 using SDL ?
- is there any option for scons to build rtech1 using SDL ?
Cheers

**Comment by kazzmir** [comment]
SDL and Allegro4 have been dropped from Paintown moving forward. Both of them use software renderers, whereas Allegro5 uses opengl. The preferred path for Paintown is to use opengl, and thus only use the Allegro5 library. There are currently no plans to support SDL2 directly, although Allegro5 can use SDL2 as a backend.

The cmake build has languished behind scons for a while, so it might take a bit of work to even get it to compile the Allegro5 version.

**Comment by WilliamTambellini** [comment]
ok thanks.
