### ISSUE TITLE
Mugen only?

### ISSUE THREAD

**Issue by Pollito001** [kazzmir/paintown#8]
Is there any way to compile just mugen?

**Comment by kazzmir** [comment]
Not currently, but its not that difficult to leave out the non-mugen parts
of the code. If you left out libpaintown-engine.a then you would just have
to adjust src/main-menu.cpp to not reference any of the menu stuff from
paintown, and only leave in the mugen stuff. It would be easiest to
directly start the mugen system by invoking Util::loadMotif() followed by
Mugen::run().

**Comment by Pollito001** [comment]
Thank for your help, but im not a coder, you can doit and send me the files?, sorry for my english

**Comment by Pollito001** [comment]
I try but i dont understand anything, please can you edit the source and send me?

**Comment by Pollito001** [comment]
Im Linux user and Mugen version for Linux is too old from 2001 and have too many compability problems. Paintown's Mugen runs good with a lot of bugs but i know paintown team will make better.

**Comment by juvinious** [comment]
If the desire is to just run mugen without going into the paintown menu first you can run the application as ./paintown mugen and it will bypass paintown.

Not sure if we'll support a standalone instance of mugen until we get r-tech1 and paintown cleaned up.
